---
engines:
  # Bundler-Audit cross references entries in your Gemfile.lock with the Ruby
  # Advisory DB https://github.com/rubysec/ruby-advisory-db.
  bundler-audit:
    enabled: true
  # Reports issues when it finds similar code blocks over a configurable mass
  # threshold
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          # Prevent reporting of e.g. validation blocks as duplication warnings;
          # a certain degree of duplication is acceptable in the name of
          # readability.
          mass_threshold: 25
  # Performs a case-sensitive search for the following strings in your project:
  # TODO, FIXME, HACK, XXX, and BUG, which are all things you should fix now,
  # not later
  fixme:
    enabled: true
  # Reek is a Code smell detector for Ruby. https://github.com/troessner/reek
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.module"
  - "**.rb"
exclude_paths:
- spec/
- vendor/
