---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          # Prevent reporting of e.g. validation blocks as duplication warnings;
          # a certain degree of duplication is acceptable in the name of
          # readability.
          mass_threshold: 25
        javascript:
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      AllCops:
        TargetRubyVersion: 2.3
  brakeman:
    enabled: false
  rubymotion:
    enabled: true
ratings:
  paths:
  - "**.module"
  - "**.rb"
exclude_paths:
- spec/
