# This file is used in conjunction with the
# [Overcommit](https://github.com/brigade/overcommit) gem. Its intended use is
# to create and manage git hooks which would then automatically run the checks
# detailed below on every commit you make.
#
# However experience has shown this can cause problems in a repo that has
# multiple people working on it, in different environments. Therefore we use it
# as a sort of 'test runner', a way of manually running the same tests against
# the project. To use locally just go with to install and setup
# $ gem install overcommit --no-ri --no-rdoc
# $ overcommit --sign
# And then just this everytime you want to run it
# $ overcommit --run
#
# For reference this file extends the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# General notes
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre_commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration

# This lets us run the tests without having to install the hooks.
verify_signatures: false

PreCommit:
  # As we're not using this to check actual commits, we can ignore these 2
  # checks
  AuthorEmail:
    enabled: false
  AuthorName:
    enabled: false

  YamlSyntax:
    enabled: true

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
      - '**/*.md'
      - '**/*.markdown'
      - '**/spec/fixtures/attachments/**/*'
      - '**/spec/cassettes/**/*'

  HardTabs:
    enabled: true
    exclude:
      - '**/vendor/assets/javascripts/**/*.js'
      - '**/spec/fixtures/attachments/**/*'
      - '**/db/migrate/*.rb'
