inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec

# Allow contexts to start with on for workflow event specs
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - "on"
    - for
