language: ruby
cache: bundler

rvm:
  - 2.3.1

addons:
  postgresql: "9.4"


# We need nodejs version >= 4 to be compatible with htmlhint >= 0.9.13
# This overwrites the system node  0.10.x
before_install:
  - nvm install node

env:
  global:
    - DB=pg
    - secure: mGy9AGSIv/OvNspycY9ghSOp9/g6wZdrHGG9l3TmAvPPQJmMn+MLnDcooX3pGKENxGIslF/5f1QX0b2ouoRXQu5jHj6EkrWjpqQE/E0xWpxhFjXoo/fE/tTFpAZKxme4wcSuFxeqfVEQ6Rk07BSG2c609AbODxnxywTaTH9rfob5HaSD+uP4E3MCPxZ6SK941pqEkfwNI9Z9g5C/oow4jn9BHP2Dy1hTzwMkfBGIsjRFzvjm7Ey4h19Zbt9YKfzjo1ZzPQ4q0ensqNJEIbryCTC/xZPl8KXA2EKwnMjDnfrhhZsX7g8FdyCs8AaeCDbCXpgXKatWsSxcjxUf6NTAg7oS7w4N/EyJguyXMROnHl+EMKSWhq74xa3dCEu5sedN5KJicHl2l1wJKKQCiZ9yZ5j86p5hqqU/B3kv9fspMuqcCIO3S4xOAg8Jv5dk0oDpnhbrWhteVryEUtwlSdBoup+MvXjbO7auBVfdx7luugBvEkT/qCAhXt4ajVJ8lQuYIJ38UKDXkblgkcjfqKG0HFTkNfOQcuxE7XoVYSXH+lxH9U3DYQeEuMH1P57ADXmUzFFEoJxjVsSfUdsFWFLK7Xl6jc6imjFxLLw8J4AmEvdyexcetZ33rl4frUhGwTsnV4cIPKcd9dlclDy5/NGKuf5gVsGNcoQgsvO1YLOKGAc=
    - secure: uj2OXO5OTNCHA/byiP0o5aXHLeF9TItHUObtuzkS2ZbbTtS38r9DPnAEkIOToSkKXeiWd4xAX2Cgql5be7JwerxwYFJo75ijHZrnBLI97LL2Kq12BEZFBbobCSKHxxSAAa9U9wcUtypb41OsFaJShvD5H7Jh11JwirHRKG6IpQzTdtEzzFXl+Vg3h0UwGdr45TtQhnent3sq636TrQV5zNN1ggr5Qk+TXrrxbH+bn92QViPxoT/U1M3qHZYplWKo1S96wMPWc/x0aGhL/aASoLwcO7/Ach8PlmqYHF3mhqs7QmWMXh8OqS0HX/xRAd5OD6BjZJ6cseAa1y+tNSQRroi8pr2QsyKu7Ji1eKHVuIpYYVfCNor0YfwKtK3b+G7iU7TUL5cdfno2NGU90/9ZkWTtSTX+UOPCmkuKV9FK88P8r0+N7hr881PS/5BtpnWJgkLtgOIDVrmOYBQpvW2qJNMYYLLPwz3BawUG8JYcEhj9P7y5NAZDSFro+0X9FdxjLWRbIdw+2WanhbMCfk53RxbUtQ5gsatTOy34ANaUyXWAmSS9ks+ZGr53WuOnV3yTnLOTXTlTB3nU2CgvTxLYGzPAfmoxLgh5RJi583ubZ4S+Q79ki/PFHD5WE3ZYt36ul+d0Y9A9IX9F0ex1ved4ZRXz7TnsZFJrVAbI/TDnD1Y=
    - secure: atEtVos72LKeP2RkvJe3Kv775yK8YkbzdzVBv03KSWkHNqxMLFxxY03J1rJpWWyW+jEGZUjYGKtH9WIWMXqJOHkIqVkbxtvHerDBjL51sWndU6h0YQgySwXilH6nY6oWXL4ul+N/nYUiEF1sJwHDr04tUMJws7707gbZsNdN4EWELfcfpSm7GyhhPKRMNoIj1LPHrEx690EnpypGAUbM4zx55wXP8hfbXxULF+dWg43/GQVgBwi0xVxhfS17c3hMfa4Ohi8j7EacNuBcTNQLIxUcpzlNxGDpLTUfkHWNZ4soBJn6ZMyNO79Far+CsbKhqe0K08Y9wIgrz741ORixAWj7x/10Al9Q7qQ3i7R0m2ZtIbhVmFc9lYAs3U/HQI08OIOOo3uaOvwQxJDFwCqRKL1ckRfZ5Wz8ax2hT75r9w2hiJQ32RNJHswQGPEhwe0jV5Q5krumdAnI7DdRt8JbO8neugeFa4gzVPc9P1tRzZ2n755ckaGRoSu18YqxX9wUL+dIzoY9vh6r8Bkv1eaNi4kTeWl8Cy1l0ObdcpzYcsCMngDdVpmsFyr3fd3i9+dRkPQLXEaK38T6PakLA+y31I48w0lBhBCNKfi9Z1fRl92EXxlYuTqb4EdDlfxHV6GfngZVBkeNOdA5/P882SmYiQ88KF8Wlq/SD6NGW1Nuz6I=

bundler_args: --binstubs=./bundler_stubs

before_script:
  - npm install -g jshint coffeelint htmlhint csslint
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create

script:
  - bundle exec rake --trace before_commit:run_without_checks
  - htmlhint -c ./.htmlhintrc ./app/**/*.html.erb
  - git config --global user.email test@example.com # overcommit Author
  - git config --global user.name "Test Example" # overcommit Author
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec overcommit --run
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
  - ls /home/travis/build/EnvironmentAgency/flood-risk-engine/spec/dummy
  - cat /home/travis/build/EnvironmentAgency/flood-risk-engine/spec/dummy/*

# Have this option to stop travis-ci building twice. Currently we have travis set to build both
# PR's and pushes. However this means when we push to a PR we have to wait for Travis to finish
# 2 builds. If we unticked 'pushes' when the PR was finally merged that would not be built. The
# brute force approach would be to untick build PR's and just build all pushes. We instead have
# gone with the approach outlined here http://stackoverflow.com/a/31882307
branches:
  only:
    - master
    - develop
