# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: 5432
  user: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["PG_DEV_DATABASE"] || "flood_risk_dummy_dev" %>

test:
  <<: *default
  database: <%= ENV["PG_TEST_DATABASE"] || "flood_risk_dummy_test" %>

local_production:
  <<: *default
  database: <%= ENV["PG_PROD_DATABASE"] || "flood_risk_dummy_prod" %>
