# Be sure to restart your server when you modify this file.

defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  airbrake_host: <%= ENV['AIRBRAKE_HOST'] %>
  airbrake_project_key: <%= ENV['AIRBRAKE_PROJECT_KEY'] || ENV['AIRBRAKE_API_KEY']%>
  pg_host: <%= ENV['PG_HOST'] %>
  pg_port: <%= ENV['PG_PORT'] %>
  pg_database: <%= ENV['PG_DATABASE'] %>
  pg_username: <%= ENV['PG_USERNAME'] %>
  pg_password: <%= ENV['PG_PASSWORD'] %>
  address_facade_server: <%= ENV['ADDRESS_FACADE_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_PORT'] %>
  address_facade_client_id: <%= ENV['ADDRESS_FACADE_CLIENT_ID'] %>
  address_facade_key: <%= ENV['ADDRESS_FACADE_KEY'] %>


defaults: &defaults

development:
  <<: *defaults
  secret_key_base: bad2f8e96dd27b54f0e86ece59c1027e8286cc120765dc7de682b13d423497c21ad641018d6f5c2cf6633f7ee6631a714f12d9ae9f5504634dec435d61d9408a
  address_facade_server: <%= ENV['ADDRESS_FACADE_TEST_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_TEST_PORT'] %>

test:
  secret_key_base: 14731485c0cfc5c2331c7de5da04126215a5e4c932cadc39da3371fbdd1b37d7e548216cdca6ecf8a3e7fa834ba5039e94a47a5c032772551607863dd632b8d6
  address_facade_server: <%= ENV['ADDRESS_FACADE_TEST_SERVER'] %>
  address_facade_port: <%= ENV['ADDRESS_FACADE_TEST_PORT'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
